# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='访问量',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=100)),
                ('PV', models.IntegerField()),
                ('UV', models.IntegerField()),
            ],
        ),
    ]
