# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_访问量'),
    ]

    operations = [
        migrations.CreateModel(
            name='可缩放的时间轴',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=100)),
                ('val', models.FloatField()),
            ],
        ),
    ]
