# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_可缩放的时间轴'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='可缩放的时间轴',
            new_name='时间轴',
        ),
    ]
